# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_air', models.IntegerField(default=0)),
                ('temp_water', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
