# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='light',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temp_air',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temp_water',
            field=models.FloatField(default=0.0),
        ),
    ]
