# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20151213_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='moised',
            field=models.IntegerField(default=0.0),
        ),
    ]
